// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: wallets.public.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blockchain int32

const (
	Blockchain_UNKNOWN Blockchain = 0
	Blockchain_POLYGON Blockchain = 1
	Blockchain_BSC     Blockchain = 2
)

// Enum value maps for Blockchain.
var (
	Blockchain_name = map[int32]string{
		0: "UNKNOWN",
		1: "POLYGON",
		2: "BSC",
	}
	Blockchain_value = map[string]int32{
		"UNKNOWN": 0,
		"POLYGON": 1,
		"BSC":     2,
	}
)

func (x Blockchain) Enum() *Blockchain {
	p := new(Blockchain)
	*p = x
	return p
}

func (x Blockchain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Blockchain) Descriptor() protoreflect.EnumDescriptor {
	return file_wallets_public_proto_enumTypes[0].Descriptor()
}

func (Blockchain) Type() protoreflect.EnumType {
	return &file_wallets_public_proto_enumTypes[0]
}

func (x Blockchain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Blockchain.Descriptor instead.
func (Blockchain) EnumDescriptor() ([]byte, []int) {
	return file_wallets_public_proto_rawDescGZIP(), []int{0}
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockchain    Blockchain             `protobuf:"varint,1,opt,name=blockchain,proto3,enum=wallets.private.Blockchain" json:"blockchain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_wallets_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallets_public_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetBlockchain() Blockchain {
	if x != nil {
		return x.Blockchain
	}
	return Blockchain_UNKNOWN
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NativeBalance string                 `protobuf:"bytes,1,opt,name=nativeBalance,proto3" json:"nativeBalance,omitempty"`
	Tokens        []*Token               `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_wallets_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallets_public_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetNativeBalance() string {
	if x != nil {
		return x.NativeBalance
	}
	return ""
}

func (x *GetBalanceResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_wallets_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_wallets_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_wallets_public_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Token) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_wallets_public_proto protoreflect.FileDescriptor

const file_wallets_public_proto_rawDesc = "" +
	"\n" +
	"\x14wallets.public.proto\x12\x0fwallets.private\"P\n" +
	"\x11GetBalanceRequest\x12;\n" +
	"\n" +
	"blockchain\x18\x01 \x01(\x0e2\x1b.wallets.private.BlockchainR\n" +
	"blockchain\"j\n" +
	"\x12GetBalanceResponse\x12$\n" +
	"\rnativeBalance\x18\x01 \x01(\tR\rnativeBalance\x12.\n" +
	"\x06tokens\x18\x02 \x03(\v2\x16.wallets.private.TokenR\x06tokens\"9\n" +
	"\x05Token\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance*/\n" +
	"\n" +
	"Blockchain\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPOLYGON\x10\x01\x12\a\n" +
	"\x03BSC\x10\x022`\n" +
	"\aWallets\x12U\n" +
	"\n" +
	"GetBalance\x12\".wallets.private.GetBalanceRequest\x1a#.wallets.private.GetBalanceResponseB\x04Z\x02./b\x06proto3"

var (
	file_wallets_public_proto_rawDescOnce sync.Once
	file_wallets_public_proto_rawDescData []byte
)

func file_wallets_public_proto_rawDescGZIP() []byte {
	file_wallets_public_proto_rawDescOnce.Do(func() {
		file_wallets_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallets_public_proto_rawDesc), len(file_wallets_public_proto_rawDesc)))
	})
	return file_wallets_public_proto_rawDescData
}

var file_wallets_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wallets_public_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wallets_public_proto_goTypes = []any{
	(Blockchain)(0),            // 0: wallets.private.Blockchain
	(*GetBalanceRequest)(nil),  // 1: wallets.private.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 2: wallets.private.GetBalanceResponse
	(*Token)(nil),              // 3: wallets.private.Token
}
var file_wallets_public_proto_depIdxs = []int32{
	0, // 0: wallets.private.GetBalanceRequest.blockchain:type_name -> wallets.private.Blockchain
	3, // 1: wallets.private.GetBalanceResponse.tokens:type_name -> wallets.private.Token
	1, // 2: wallets.private.Wallets.GetBalance:input_type -> wallets.private.GetBalanceRequest
	2, // 3: wallets.private.Wallets.GetBalance:output_type -> wallets.private.GetBalanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wallets_public_proto_init() }
func file_wallets_public_proto_init() {
	if File_wallets_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallets_public_proto_rawDesc), len(file_wallets_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallets_public_proto_goTypes,
		DependencyIndexes: file_wallets_public_proto_depIdxs,
		EnumInfos:         file_wallets_public_proto_enumTypes,
		MessageInfos:      file_wallets_public_proto_msgTypes,
	}.Build()
	File_wallets_public_proto = out.File
	file_wallets_public_proto_goTypes = nil
	file_wallets_public_proto_depIdxs = nil
}
